APP_TITLE = "CAISSE WAC BRAND"
STAND_NAMES = ["Stand VVIP", "VIP", "ZONE 2"]
PAYMENT_MODES = ["ESPECE", "TPE"] # Nouveau
SPREADSHEET_NAME = "Caisse_Merchandising"
SHEET_SALES = "Ventes"
SHEET_PRODUCTS = "Produits"
